[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
sol_overlaunch = "5zws23e8bohUwsmmGRR6AeXoGjXSyx2RPxNGCHVU1QpB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
